apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-capstone
  labels:
    app: cloud-devops-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-devops-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloud-devops-capstone
    spec:
      containers:
        - image: pawankolhe/udacity-capstone
          imagePullPolicy: Always
          name: cloud-devops-capstone
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-devops-capstone
  labels:
    app: cloud-devops-capstone
spec:
  type: LoadBalancer
  selector:
    app: cloud-devops-capstone
  ports:
    - port: 3000
      targetPort: 3000
      # nodePort: 30000
      protocol: TCP